In [1]:
import random

from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')
import pickle
import sklearn.metrics as metrics

### functions

In [2]:
def edge_features(node_emb_1, node_emb_2, operator):
    node_emb_1 = np.asfarray(node_emb_1,float)
    node_emb_2 = np.asfarray(node_emb_2, float)
    # combine two nodes' embeddings with specificed operator
    if operator == 'Average':
        edge = [((x + y) / 2.0) for x,y in zip(node_emb_1, node_emb_2)]
    elif operator == 'Hadamard':
        edge = [(x * y) for x,y in zip(node_emb_1, node_emb_2)]
    elif operator == 'Weighted-L1':
        edge = [abs(x - y) for x,y in zip(node_emb_1, node_emb_2)]
    elif operator == 'Weighted-L2':
        edge = [abs(x - y)**2 for x,y in zip(node_emb_1, node_emb_2)]
    elif operator == 'Concat':
        edge = np.concatenate((node_emb_1, node_emb_2), axis=None) 
    else:
        print("Generate edge features: Operator not supported")
        print("Use default operator: Weighted-L1")
        edge = [abs(x - y) for x,y in zip(node_emb_1, node_emb_2)]
        
    return edge
def generate_edge_features(edge_list, node_embeddings, operator):
    edge_features_mtx = []
    
    # generate features for each edge in the list
    for node_index_1, node_index_2 in edge_list:
        node_emb_1 = node_embeddings[node_index_1-1]
        node_emb_2 = node_embeddings[node_index_2-1]
        
        edge_features_mtx.append(edge_features(node_emb_1, node_emb_2, operator))
        
    return edge_features_mtx

def generate_train_set(graph_train, num_edge_sample, node_embeddings, edge_operator,):
    edge_list = list(graph_train.edges)
    num_nodes = graph_train.number_of_nodes()
    
    train_edges = []
    train_edges_labels = [1] * num_edge_sample + [0] * num_edge_sample
    
    random.seed(0)
    
    # sample edges with label 1 (true edges)
    for edge_num in range(num_edge_sample):
        rand_index = random.randint(0, len(edge_list) - 1)
        
        #train_edges.append(tuple(edge_list[rand_index]))
        train_edges.append(edge_list[rand_index])
    non_edge_num = 0
    
    # sample edges with label 0 (non-exist edges)
    while(non_edge_num < num_edge_sample):
        rand_nodes = tuple(np.random.randint(low=0,high=num_nodes, size=2))
        
        if rand_nodes not in edge_list:
            train_edges.append(rand_nodes)
            non_edge_num += 1

    train_edges_features_mtx = generate_edge_features(train_edges, node_embeddings, edge_operator)
            
    return train_edges, train_edges_features_mtx, train_edges_labels

def generate_test_set(graph_test, node_embeddings, edge_operator):
    edge_list = graph_test.edges
    nodes_with_edge = set()
    
    for edge in edge_list:
        nodes_with_edge.add(edge[0])
        nodes_with_edge.add(edge[1])
    
    num_nodes = graph_test.number_of_nodes()
    
    test_edges = []
    test_edges_labels = []
    
    num_edge_sample = len(edge_list)
    non_edge_num = 0 
    # sample edges with label 0 (non-exist edges)
    
    while(non_edge_num < num_edge_sample):
        rand_nodes = tuple(np.random.randint(low=0,high=num_nodes, size=2))
        
        if rand_nodes not in edge_list:
            test_edges.append(rand_nodes)
            test_edges_labels.append(0)
            non_edge_num += 1
        
    for edge in edge_list:
        test_edges.append(edge)
        test_edges_labels.append(1)
    
    test_edges_features_mtx = generate_edge_features(test_edges, node_embeddings, edge_operator)
    
    return test_edges, test_edges_features_mtx, test_edges_labels

def build_clf(feature_mtx, response_vec):
   
    logistic_regression_model = LogisticRegression(random_state = 0,max_iter=5000,solver='liblinear',verbose=1,tol=1e-6)
    binary_clf = logistic_regression_model.fit(feature_mtx, response_vec)
    
    return binary_clf

def pred_links(feature_mtx, LR_clf):
    predict_edges_labels = LR_clf.predict(feature_mtx)
    
    return predict_edges_labels

def precision_recall(predict_labels, true_labels):
    true_positive  = false_positive = 0
    true_negative =  false_negative = 0
    
    for p_label, true_label in zip(predict_labels, true_labels):
        
        #print(p_label,true_label)
        if p_label == true_label and true_label == 1:
            true_positive += 1
        elif p_label == true_label and true_label == 0:
            true_negative += 1
        elif p_label != true_label and true_label == 1:
            false_negative += 1
        elif p_label != true_label and true_label == 0:
            false_positive += 1

    print("TP: ", true_positive)
    print("TN: ", true_negative)
    print("FP: ", false_positive)
    print("FN: ", false_negative)
    
    precision = recall = 0
    try:
        precision = true_positive / (true_positive + false_positive)
        recall = true_positive / (true_positive + false_negative)
        if (precision + recall) != 0.0:
            f1 = 2 * (precision * recall) / (precision + recall)
            print("F1: {}".format(f1))            
    except:
        print("F1: Divide-by-zero")
    
    cm = metrics.confusion_matrix(true_labels, predict_labels)
    print(cm)
    print(metrics.classification_report(true_labels, predict_labels))
    map = metrics.average_precision_score(true_labels, predict_labels)
    print('Mean Average Precision: {}'.format(map))
    fpr, tpr, thresholds = metrics.roc_curve(true_labels, predict_labels)
    roc_auc = metrics.auc(fpr, tpr)
    print('Area Under ROC Curve: {}'.format(roc_auc))
    
    return precision, recall

### RM- Monthly
### load data

In [3]:
# load the training and testing graph
with open('../RM_monthly.pkl', 'rb') as file:
    graphs = pickle.load(file)
graph_train = graphs[-2]
graph_test = graphs[-1]

# parameters
num_edge_sample = 400

In [4]:
num_snapshots = len(graphs)
num_snapshots

11

In [5]:
emb_list = []
for i in range(num_snapshots):
    file = '../RM_N2V_1_4_emb/rm-month/rm_month_' + str(i) + '.npy'
    node_embedding = np.load(file)
    emb_list.append(node_embedding)
print(len(emb_list))

11


### independent / no combination

In [6]:
node_embeddings_training = emb_list[-3]
node_embeddings_testing = emb_list[-2]

In [7]:
for edge_operator in ['Average','Hadamard','Weighted-L1','Weighted-L2', 'Concat']:
    # generate the training set
    train_edges, train_edges_features_mtx, train_edges_labels = generate_train_set(graph_train, num_edge_sample, node_embeddings_training, edge_operator)
    # generate the testing set
    test_edges, test_edges_features_mtx, test_edges_labels = generate_test_set(graph_test, node_embeddings_testing, edge_operator)

    LR_clf = build_clf(train_edges_features_mtx, train_edges_labels)

    print("Edge Operator: {}".format(edge_operator))
    predict_edges_labels = pred_links(test_edges_features_mtx, LR_clf)
    precision, recall = precision_recall(list(predict_edges_labels), list(test_edges_labels))
    print('Precision: ', precision)
    print('Recall: ', recall)

[LibLinear]Edge Operator: Average
TP:  0
TN:  222
FP:  0
FN:  222
F1: Divide-by-zero
[[222   0]
 [222   0]]
              precision    recall  f1-score   support

           0       0.50      1.00      0.67       222
           1       0.00      0.00      0.00       222

    accuracy                           0.50       444
   macro avg       0.25      0.50      0.33       444
weighted avg       0.25      0.50      0.33       444

Mean Average Precision: 0.5
Area Under ROC Curve: 0.5
Precision:  0
Recall:  0


/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


[LibLinear]Edge Operator: Hadamard
TP:  103
TN:  222
FP:  0
FN:  119
F1: 0.6338461538461538
[[222   0]
 [119 103]]
              precision    recall  f1-score   support

           0       0.65      1.00      0.79       222
           1       1.00      0.46      0.63       222

    accuracy                           0.73       444
   macro avg       0.83      0.73      0.71       444
weighted avg       0.83      0.73      0.71       444

Mean Average Precision: 0.7319819819819819
Area Under ROC Curve: 0.7319819819819819
Precision:  1.0
Recall:  0.46396396396396394
[LibLinear]Edge Operator: Weighted-L1
TP:  204
TN:  203
FP:  19
FN:  18
F1: 0.9168539325842698
[[203  19]
 [ 18 204]]
              precision    recall  f1-score   support

           0       0.92      0.91      0.92       222
           1       0.91      0.92      0.92       222

    accuracy                           0.92       444
   macro avg       0.92      0.92      0.92       444
weighted avg       0.92      0.92      

/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


### sum

In [8]:
for i in range(len(emb_list)):
    emb_list[i] = np.asfarray(emb_list[i],float)
node_embeddings_training = np.sum(np.asarray(emb_list[0:-2]),axis=0)
node_embeddings_testing = np.sum(np.asarray(emb_list[0:-1]),axis=0)

In [9]:
for edge_operator in ['Average', 'Hadamard','Weighted-L1','Weighted-L2', 'Concat']:
    # generate the training set
    train_edges, train_edges_features_mtx, train_edges_labels = generate_train_set(graph_train, num_edge_sample, node_embeddings_training, edge_operator)
    # generate the testing set
    test_edges, test_edges_features_mtx, test_edges_labels = generate_test_set(graph_test, node_embeddings_testing, edge_operator)

    LR_clf = build_clf(train_edges_features_mtx, train_edges_labels)

    print("Edge Operator: {}".format(edge_operator))
    predict_edges_labels = pred_links(test_edges_features_mtx, LR_clf)
    precision, recall = precision_recall(list(predict_edges_labels), list(test_edges_labels))
    print('Precision: ', precision)
    print('Recall: ', recall)

[LibLinear]Edge Operator: Average
TP:  222
TN:  217
FP:  5
FN:  0
F1: 0.9888641425389755
[[217   5]
 [  0 222]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       222
           1       0.98      1.00      0.99       222

    accuracy                           0.99       444
   macro avg       0.99      0.99      0.99       444
weighted avg       0.99      0.99      0.99       444

Mean Average Precision: 0.9779735682819384
Area Under ROC Curve: 0.9887387387387387
Precision:  0.9779735682819384
Recall:  1.0
[LibLinear]Edge Operator: Hadamard
TP:  148
TN:  203
FP:  19
FN:  74
F1: 0.7609254498714653
[[203  19]
 [ 74 148]]
              precision    recall  f1-score   support

           0       0.73      0.91      0.81       222
           1       0.89      0.67      0.76       222

    accuracy                           0.79       444
   macro avg       0.81      0.79      0.79       444
weighted avg       0.81      0.79      0.79   

### expdecay

In [22]:
exps = [np.exp(-i * 0.5) for i in range(1,17)]
node_embeddings_training = np.zeros((emb_list[0]).shape) 
for c,e in zip(emb_list[0:-2],exps[:-1]):
    node_embeddings_training += e * c

In [23]:
node_embeddings_testing = np.zeros((emb_list[0]).shape) 
for c,e in zip(emb_list[0:-1],exps[:-1]):
    node_embeddings_testing += e * c 

In [24]:
for edge_operator in [ 'Average', 'Hadamard','Weighted-L1','Weighted-L2', 'Concat']:
    # generate the training set
    train_edges, train_edges_features_mtx, train_edges_labels = generate_train_set(graph_train, num_edge_sample, node_embeddings_training, edge_operator)
    # generate the testing set
    test_edges, test_edges_features_mtx, test_edges_labels = generate_test_set(graph_test, node_embeddings_testing, edge_operator)

    LR_clf = build_clf(train_edges_features_mtx, train_edges_labels)

    print("Edge Operator: {}".format(edge_operator))
    predict_edges_labels = pred_links(test_edges_features_mtx, LR_clf)
    precision, recall = precision_recall(list(predict_edges_labels), list(test_edges_labels))
    print('Precision: ', precision)
    print('Recall: ', recall)

[LibLinear]Edge Operator: Average
TP:  222
TN:  208
FP:  14
FN:  0
F1: 0.9694323144104803
[[208  14]
 [  0 222]]
              precision    recall  f1-score   support

           0       1.00      0.94      0.97       222
           1       0.94      1.00      0.97       222

    accuracy                           0.97       444
   macro avg       0.97      0.97      0.97       444
weighted avg       0.97      0.97      0.97       444

Mean Average Precision: 0.940677966101695
Area Under ROC Curve: 0.9684684684684685
Precision:  0.940677966101695
Recall:  1.0
[LibLinear]Edge Operator: Hadamard
TP:  93
TN:  208
FP:  14
FN:  129
F1: 0.5653495440729484
[[208  14]
 [129  93]]
              precision    recall  f1-score   support

           0       0.62      0.94      0.74       222
           1       0.87      0.42      0.57       222

    accuracy                           0.68       444
   macro avg       0.74      0.68      0.65       444
weighted avg       0.74      0.68      0.65    

### RM - Weekly
### load data

In [25]:
# load the training and testing graph
with open('../RM_weekly.pkl', 'rb') as file:
    graphs = pickle.load(file)
graph_train = graphs[-2]
graph_test = graphs[-1]

# parameters
num_edge_sample = 400

In [26]:
num_snapshots = len(graphs)
num_snapshots

51

In [27]:
emb_list = []
for i in range(num_snapshots):
    file = '../RM_N2V_1_4_emb/rm-week/rm_week_' + str(i) + '.npy'
    node_embedding = np.load(file)
    emb_list.append(node_embedding)
print(len(emb_list))

51


### independent / no combination

In [28]:
node_embeddings_training = emb_list[-3]
node_embeddings_testing = emb_list[-2]

In [29]:
for edge_operator in ['Average', 'Hadamard','Weighted-L1','Weighted-L2', 'Concat']:
    # generate the training set
    train_edges, train_edges_features_mtx, train_edges_labels = generate_train_set(graph_train, num_edge_sample, node_embeddings_training, edge_operator)
    # generate the testing set
    test_edges, test_edges_features_mtx, test_edges_labels = generate_test_set(graph_test, node_embeddings_testing, edge_operator)

    LR_clf = build_clf(train_edges_features_mtx, train_edges_labels)

    print("Edge Operator: {}".format(edge_operator))
    predict_edges_labels = pred_links(test_edges_features_mtx, LR_clf)
    precision, recall = precision_recall(list(predict_edges_labels), list(test_edges_labels))
    print('Precision: ', precision)
    print('Recall: ', recall)

[LibLinear]Edge Operator: Average
TP:  0
TN:  14
FP:  0
FN:  14
F1: Divide-by-zero
[[14  0]
 [14  0]]
              precision    recall  f1-score   support

           0       0.50      1.00      0.67        14
           1       0.00      0.00      0.00        14

    accuracy                           0.50        28
   macro avg       0.25      0.50      0.33        28
weighted avg       0.25      0.50      0.33        28

Mean Average Precision: 0.5
Area Under ROC Curve: 0.5
Precision:  0
Recall:  0
[LibLinear]Edge Operator: Hadamard
TP:  10
TN:  14
FP:  0
FN:  4
F1: 0.8333333333333333
[[14  0]
 [ 4 10]]
              precision    recall  f1-score   support

           0       0.78      1.00      0.88        14
           1       1.00      0.71      0.83        14

    accuracy                           0.86        28
   macro avg       0.89      0.86      0.85        28
weighted avg       0.89      0.86      0.85        28

Mean Average Precision: 0.8571428571428572
Area Under ROC 

/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


[LibLinear]Edge Operator: Weighted-L1
TP:  4
TN:  14
FP:  0
FN:  10
F1: 0.4444444444444445
[[14  0]
 [10  4]]
              precision    recall  f1-score   support

           0       0.58      1.00      0.74        14
           1       1.00      0.29      0.44        14

    accuracy                           0.64        28
   macro avg       0.79      0.64      0.59        28
weighted avg       0.79      0.64      0.59        28

Mean Average Precision: 0.6428571428571428
Area Under ROC Curve: 0.6428571428571428
Precision:  1.0
Recall:  0.2857142857142857
[LibLinear]Edge Operator: Weighted-L2
TP:  4
TN:  14
FP:  0
FN:  10
F1: 0.4444444444444445
[[14  0]
 [10  4]]
              precision    recall  f1-score   support

           0       0.58      1.00      0.74        14
           1       1.00      0.29      0.44        14

    accuracy                           0.64        28
   macro avg       0.79      0.64      0.59        28
weighted avg       0.79      0.64      0.59        28

/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


### sum

In [30]:
for i in range(len(emb_list)):
    emb_list[i] = np.asfarray(emb_list[i],float)
node_embeddings_training = np.sum(np.asarray(emb_list[0:-2]),axis=0)
node_embeddings_testing = np.sum(np.asarray(emb_list[0:-1]),axis=0)

In [31]:
for edge_operator in ['Average', 'Hadamard','Weighted-L1','Weighted-L2', 'Concat']:
    # generate the training set
    train_edges, train_edges_features_mtx, train_edges_labels = generate_train_set(graph_train, num_edge_sample, node_embeddings_training, edge_operator)
    # generate the testing set
    test_edges, test_edges_features_mtx, test_edges_labels = generate_test_set(graph_test, node_embeddings_testing, edge_operator)

    LR_clf = build_clf(train_edges_features_mtx, train_edges_labels)

    print("Edge Operator: {}".format(edge_operator))
    predict_edges_labels = pred_links(test_edges_features_mtx, LR_clf)
    precision, recall = precision_recall(list(predict_edges_labels), list(test_edges_labels))
    print('Precision: ', precision)
    print('Recall: ', recall)

[LibLinear]Edge Operator: Average
TP:  14
TN:  14
FP:  0
FN:  0
F1: 1.0
[[14  0]
 [ 0 14]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        14

    accuracy                           1.00        28
   macro avg       1.00      1.00      1.00        28
weighted avg       1.00      1.00      1.00        28

Mean Average Precision: 1.0
Area Under ROC Curve: 1.0
Precision:  1.0
Recall:  1.0
[LibLinear]Edge Operator: Hadamard
TP:  8
TN:  14
FP:  0
FN:  6
F1: 0.7272727272727273
[[14  0]
 [ 6  8]]
              precision    recall  f1-score   support

           0       0.70      1.00      0.82        14
           1       1.00      0.57      0.73        14

    accuracy                           0.79        28
   macro avg       0.85      0.79      0.78        28
weighted avg       0.85      0.79      0.78        28

Mean Average Precision: 0.7857142857142857
Area Under ROC Curve: 0

### expdecay

In [36]:
exps = [np.exp(-i * 0.3) for i in range(1,74)]
node_embeddings_training = np.zeros((emb_list[0]).shape) 
for c,e in zip(emb_list[0:-2],exps[:-1]):
    node_embeddings_training += e * c 
node_embeddings_testing = np.zeros((emb_list[0]).shape) 
for c,e in zip(emb_list[0:-1],exps[:-1]):
    node_embeddings_testing += e * c 

In [37]:
for edge_operator in ['Average', 'Hadamard','Weighted-L1','Weighted-L2', 'Concat']:
    # generate the training set
    train_edges, train_edges_features_mtx, train_edges_labels = generate_train_set(graph_train, num_edge_sample, node_embeddings_training, edge_operator)
    # generate the testing set
    test_edges, test_edges_features_mtx, test_edges_labels = generate_test_set(graph_test, node_embeddings_testing, edge_operator)

    LR_clf = build_clf(train_edges_features_mtx, train_edges_labels)

    print("Edge Operator: {}".format(edge_operator))
    predict_edges_labels = pred_links(test_edges_features_mtx, LR_clf)
    precision, recall = precision_recall(list(predict_edges_labels), list(test_edges_labels))
    print('Precision: ', precision)
    print('Recall: ', recall)

[LibLinear]Edge Operator: Average
TP:  14
TN:  13
FP:  1
FN:  0
F1: 0.9655172413793104
[[13  1]
 [ 0 14]]
              precision    recall  f1-score   support

           0       1.00      0.93      0.96        14
           1       0.93      1.00      0.97        14

    accuracy                           0.96        28
   macro avg       0.97      0.96      0.96        28
weighted avg       0.97      0.96      0.96        28

Mean Average Precision: 0.9333333333333333
Area Under ROC Curve: 0.9642857142857143
Precision:  0.9333333333333333
Recall:  1.0
[LibLinear]Edge Operator: Hadamard
TP:  6
TN:  14
FP:  0
FN:  8
F1: 0.6
[[14  0]
 [ 8  6]]
              precision    recall  f1-score   support

           0       0.64      1.00      0.78        14
           1       1.00      0.43      0.60        14

    accuracy                           0.71        28
   macro avg       0.82      0.71      0.69        28
weighted avg       0.82      0.71      0.69        28

Mean Average Precisio

# RM - Equal
### load data

In [38]:
# load the training and testing graph
with open('../RM_equaledge.pkl', 'rb') as file:
    graphs = pickle.load(file)
graph_train = graphs[-2]
graph_test = graphs[-1]

# parameters
num_edge_sample = 400

In [39]:
num_snapshots = len(graphs)
num_snapshots

51

In [40]:
emb_list = []
for i in range(num_snapshots):
    file = '../RM_N2V_1_4_emb/rm-equal/msg_equal_' + str(i) + '.npy'
    node_embedding = np.load(file)
    emb_list.append(node_embedding)
print(len(emb_list))

51


### independent / no combination

In [41]:
node_embeddings_training = emb_list[-3]
node_embeddings_testing = emb_list[-2]

In [42]:
for edge_operator in ['Average','Hadamard','Weighted-L1','Weighted-L2', 'Concat']:
    # generate the training set
    train_edges, train_edges_features_mtx, train_edges_labels = generate_train_set(graph_train, num_edge_sample, node_embeddings_training, edge_operator)
    # generate the testing set
    test_edges, test_edges_features_mtx, test_edges_labels = generate_test_set(graph_test, node_embeddings_testing, edge_operator)

    LR_clf = build_clf(train_edges_features_mtx, train_edges_labels)

    print("Edge Operator: {}".format(edge_operator))
    predict_edges_labels = pred_links(test_edges_features_mtx, LR_clf)
    precision, recall = precision_recall(list(predict_edges_labels), list(test_edges_labels))
    print('Precision: ', precision)
    print('Recall: ', recall)

[LibLinear]Edge Operator: Average
TP:  127
TN:  320
FP:  2
FN:  195
F1: 0.5631929046563193
[[320   2]
 [195 127]]
              precision    recall  f1-score   support

           0       0.62      0.99      0.76       322
           1       0.98      0.39      0.56       322

    accuracy                           0.69       644
   macro avg       0.80      0.69      0.66       644
weighted avg       0.80      0.69      0.66       644

Mean Average Precision: 0.6910900861861429
Area Under ROC Curve: 0.6940993788819875
Precision:  0.9844961240310077
Recall:  0.3944099378881988
[LibLinear]Edge Operator: Hadamard
TP:  123
TN:  320
FP:  2
FN:  199
F1: 0.5503355704697986
[[320   2]
 [199 123]]
              precision    recall  f1-score   support

           0       0.62      0.99      0.76       322
           1       0.98      0.38      0.55       322

    accuracy                           0.69       644
   macro avg       0.80      0.69      0.66       644
weighted avg       0.80      

### sum

In [43]:
for i in range(len(emb_list)):
    emb_list[i] = np.asfarray(emb_list[i],float)
node_embeddings_training = np.sum(np.asarray(emb_list[0:-2]),axis=0)
node_embeddings_testing = np.sum(np.asarray(emb_list[0:-1]),axis=0)

In [44]:
for edge_operator in ['Average', 'Hadamard','Weighted-L1','Weighted-L2', 'Concat']:
    # generate the training set
    train_edges, train_edges_features_mtx, train_edges_labels = generate_train_set(graph_train, num_edge_sample, node_embeddings_training, edge_operator)
    # generate the testing set
    test_edges, test_edges_features_mtx, test_edges_labels = generate_test_set(graph_test, node_embeddings_testing, edge_operator)

    LR_clf = build_clf(train_edges_features_mtx, train_edges_labels)

    print("Edge Operator: {}".format(edge_operator))
    predict_edges_labels = pred_links(test_edges_features_mtx, LR_clf)
    precision, recall = precision_recall(list(predict_edges_labels), list(test_edges_labels))
    print('Precision: ', precision)
    print('Recall: ', recall)

[LibLinear]Edge Operator: Average
TP:  321
TN:  314
FP:  8
FN:  1
F1: 0.9861751152073733
[[314   8]
 [  1 321]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       322
           1       0.98      1.00      0.99       322

    accuracy                           0.99       644
   macro avg       0.99      0.99      0.99       644
weighted avg       0.99      0.99      0.99       644

Mean Average Precision: 0.9742066114142235
Area Under ROC Curve: 0.9860248447204969
Precision:  0.9756838905775076
Recall:  0.9968944099378882
[LibLinear]Edge Operator: Hadamard
TP:  215
TN:  293
FP:  29
FN:  107
F1: 0.7597173144876324
[[293  29]
 [107 215]]
              precision    recall  f1-score   support

           0       0.73      0.91      0.81       322
           1       0.88      0.67      0.76       322

    accuracy                           0.79       644
   macro avg       0.81      0.79      0.79       644
weighted avg       0.81      0

### expdecay

In [49]:
exps = [np.exp(-i * 0.3) for i in range(1,17)]
node_embeddings_training = np.zeros((emb_list[0]).shape) 
for c,e in zip(emb_list[0:-2],exps[:-1]):
    node_embeddings_training += e * c 
node_embeddings_testing = np.zeros((emb_list[0]).shape) 
for c,e in zip(emb_list[0:-1],exps[:-1]):
    node_embeddings_testing += e * c 

In [50]:
for edge_operator in ['Average', 'Hadamard','Weighted-L1','Weighted-L2', 'Concat']:
    # generate the training set
    train_edges, train_edges_features_mtx, train_edges_labels = generate_train_set(graph_train, num_edge_sample, node_embeddings_training, edge_operator)
    # generate the testing set
    test_edges, test_edges_features_mtx, test_edges_labels = generate_test_set(graph_test, node_embeddings_testing, edge_operator)

    LR_clf = build_clf(train_edges_features_mtx, train_edges_labels)

    print("Edge Operator: {}".format(edge_operator))
    predict_edges_labels = pred_links(test_edges_features_mtx, LR_clf)
    precision, recall = precision_recall(list(predict_edges_labels), list(test_edges_labels))
    print('Precision: ', precision)
    print('Recall: ', recall)

[LibLinear]Edge Operator: Average
TP:  319
TN:  317
FP:  5
FN:  3
F1: 0.9876160990712074
[[317   5]
 [  3 319]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       322
           1       0.98      0.99      0.99       322

    accuracy                           0.99       644
   macro avg       0.99      0.99      0.99       644
weighted avg       0.99      0.99      0.99       644

Mean Average Precision: 0.9800532934590906
Area Under ROC Curve: 0.9875776397515529
Precision:  0.9845679012345679
Recall:  0.9906832298136646
[LibLinear]Edge Operator: Hadamard
TP:  106
TN:  318
FP:  4
FN:  216
F1: 0.49074074074074076
[[318   4]
 [216 106]]
              precision    recall  f1-score   support

           0       0.60      0.99      0.74       322
           1       0.96      0.33      0.49       322

    accuracy                           0.66       644
   macro avg       0.78      0.66      0.62       644
weighted avg       0.78      0

### Email-EU - Equal Weekly
### load data

In [56]:
# load the training and testing graph
with open('../data/email_EU/email_equal_weekly_dir.pkl', 'rb') as file:
    graphs = pickle.load(file)
graph_train = graphs[-2]
graph_test = graphs[-1]

# parameters
num_edge_sample = 400

In [57]:
num_snapshots = len(graphs)
num_snapshots

74

In [59]:
emb_list = []
for i in range(num_snapshots):
    file = '../data/email_EU/embeddings/em-email-equal-week-' + str(i) + '.npy'
    node_embedding = np.load(file)
    emb_list.append(node_embedding)
print(len(emb_list))

74


In [60]:
node_embeddings_training = emb_list[-3]
node_embeddings_testing = emb_list[-2]

In [61]:
for edge_operator in ['Average','Hadamard','Weighted-L1','Weighted-L2', 'Concat']:
    # generate the training set
    train_edges, train_edges_features_mtx, train_edges_labels = generate_train_set(graph_train, num_edge_sample, node_embeddings_training, edge_operator)
    # generate the testing set
    test_edges, test_edges_features_mtx, test_edges_labels = generate_test_set(graph_test, node_embeddings_testing, edge_operator)

    LR_clf = build_clf(train_edges_features_mtx, train_edges_labels)

    print("Edge Operator: {}".format(edge_operator))
    predict_edges_labels = pred_links(test_edges_features_mtx, LR_clf)
    precision, recall = precision_recall(list(predict_edges_labels), list(test_edges_labels))
    print('Precision: ', precision)
    print('Recall: ', recall)

[LibLinear]Edge Operator: Average
TP:  242
TN:  1948
FP:  197
FN:  1903
F1: 0.1873065015479876
[[1948  197]
 [1903  242]]
              precision    recall  f1-score   support

           0       0.51      0.91      0.65      2145
           1       0.55      0.11      0.19      2145

   micro avg       0.51      0.51      0.51      4290
   macro avg       0.53      0.51      0.42      4290
weighted avg       0.53      0.51      0.42      4290

Mean Average Precision: 0.5057823725249693
Area Under ROC Curve: 0.5104895104895105
Precision:  0.55125284738041
Recall:  0.11282051282051282
[LibLinear]Edge Operator: Hadamard
TP:  1673
TN:  427
FP:  1718
FN:  472
F1: 0.604407514450867
[[ 427 1718]
 [ 472 1673]]
              precision    recall  f1-score   support

           0       0.47      0.20      0.28      2145
           1       0.49      0.78      0.60      2145

   micro avg       0.49      0.49      0.49      4290
   macro avg       0.48      0.49      0.44      4290
weighted avg   

### sum

In [62]:
for i in range(len(emb_list)):
    emb_list[i] = np.asfarray(emb_list[i],float)
node_embeddings_training = np.sum(np.asarray(emb_list[0:-2]),axis=0)
node_embeddings_testing = np.sum(np.asarray(emb_list[0:-1]),axis=0)

In [63]:
for edge_operator in ['Average', 'Hadamard','Weighted-L1','Weighted-L2', 'Concat']:
    # generate the training set
    train_edges, train_edges_features_mtx, train_edges_labels = generate_train_set(graph_train, num_edge_sample, node_embeddings_training, edge_operator)
    # generate the testing set
    test_edges, test_edges_features_mtx, test_edges_labels = generate_test_set(graph_test, node_embeddings_testing, edge_operator)

    LR_clf = build_clf(train_edges_features_mtx, train_edges_labels)

    print("Edge Operator: {}".format(edge_operator))
    predict_edges_labels = pred_links(test_edges_features_mtx, LR_clf)
    precision, recall = precision_recall(list(predict_edges_labels), list(test_edges_labels))
    print('Precision: ', precision)
    print('Recall: ', recall)

[LibLinear]Edge Operator: Average
TP:  1281
TN:  1369
FP:  776
FN:  864
F1: 0.609709662065683
[[1369  776]
 [ 864 1281]]
              precision    recall  f1-score   support

           0       0.61      0.64      0.63      2145
           1       0.62      0.60      0.61      2145

   micro avg       0.62      0.62      0.62      4290
   macro avg       0.62      0.62      0.62      4290
weighted avg       0.62      0.62      0.62      4290

Mean Average Precision: 0.5733075869196433
Area Under ROC Curve: 0.6177156177156178
Precision:  0.6227515799708313
Recall:  0.5972027972027972
[LibLinear]Edge Operator: Hadamard
TP:  1237
TN:  1017
FP:  1128
FN:  908
F1: 0.5485587583148559
[[1017 1128]
 [ 908 1237]]
              precision    recall  f1-score   support

           0       0.53      0.47      0.50      2145
           1       0.52      0.58      0.55      2145

   micro avg       0.53      0.53      0.53      4290
   macro avg       0.53      0.53      0.52      4290
weighted avg 

### expdecay

In [68]:
exps = [np.exp(-i * 0.3) for i in range(1,28)]
node_embeddings_training = np.zeros((emb_list[0]).shape) 
for c,e in zip(emb_list[0:-2],exps[:-1]):
    node_embeddings_training += e * c 
node_embeddings_testing = np.zeros((emb_list[0]).shape) 
for c,e in zip(emb_list[0:-1],exps[:-1]):
    node_embeddings_testing += e * c 

In [69]:
for edge_operator in ['Average', 'Hadamard','Weighted-L1','Weighted-L2', 'Concat']:
    # generate the training set
    train_edges, train_edges_features_mtx, train_edges_labels = generate_train_set(graph_train, num_edge_sample, node_embeddings_training, edge_operator)
    # generate the testing set
    test_edges, test_edges_features_mtx, test_edges_labels = generate_test_set(graph_test, node_embeddings_testing, edge_operator)

    LR_clf = build_clf(train_edges_features_mtx, train_edges_labels)

    print("Edge Operator: {}".format(edge_operator))
    predict_edges_labels = pred_links(test_edges_features_mtx, LR_clf)
    precision, recall = precision_recall(list(predict_edges_labels), list(test_edges_labels))
    print('Precision: ', precision)
    print('Recall: ', recall)

[LibLinear]Edge Operator: Average
TP:  1306
TN:  1276
FP:  869
FN:  839
F1: 0.6046296296296296
[[1276  869]
 [ 839 1306]]
              precision    recall  f1-score   support

           0       0.60      0.59      0.60      2145
           1       0.60      0.61      0.60      2145

   micro avg       0.60      0.60      0.60      4290
   macro avg       0.60      0.60      0.60      4290
weighted avg       0.60      0.60      0.60      4290

Mean Average Precision: 0.5611657155105432
Area Under ROC Curve: 0.6018648018648018
Precision:  0.6004597701149426
Recall:  0.6088578088578088
[LibLinear]Edge Operator: Hadamard
TP:  1529
TN:  696
FP:  1449
FN:  616
F1: 0.5969158696076519
[[ 696 1449]
 [ 616 1529]]
              precision    recall  f1-score   support

           0       0.53      0.32      0.40      2145
           1       0.51      0.71      0.60      2145

   micro avg       0.52      0.52      0.52      4290
   macro avg       0.52      0.52      0.50      4290
weighted avg 